name: Rebase Upstream
on:
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 100  # greater than the number of commits you made
        token: ${{ secrets.GH_TOKEN }}
    - uses: imba-tjd/rebase-upstream-action@master
      with:  # all args are optional
        upstream: moeakwak/chatgpt-web-share
        branch:  dev
